CREATE TABLE professor(
	cpf VARCHAR(11) NOT NULL,
	nome VARCHAR(100) NOT NULL,
	data_nasc DATE,
	salario NUMERIC(10, 2) NOT NULL CHECK (salario > 0),
	idade INTEGER NOT NULL CHECK (idade BETWEEN 0 AND 100),
	CONSTRAINT "pk_prof" PRIMARY KEY (cpf)
);

CREATE TABLE aluno(
	cpf VARCHAR(11) NOT NULL,
	nome VARCHAR(100) NOT NULL,
	turma VARCHAR(100) NOT NULL,
	semestre INTEGER NOT NULL CHECK (semestre BETWEEN 1 AND 10),
	CONSTRAINT "pk_aluno" PRIMARY KEY (cpf)
);

CREATE TABLE disciplina(
	cod INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	cpf VARCHAR(11) NOT NULL,
	nome VARCHAR(100) NOT NULL,
	descricao VARCHAR(300) NOT NULL,
	CONSTRAINT "pk_disc" PRIMARY KEY (cod),
	CONSTRAINT "fk_disc_aluno" FOREIGN KEY(cpf)
	REFERENCES professor(cpf)
);

CREATE TABLE questao(
	cod INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	tipo VARCHAR(10) NOT NULL,
	pergunta VARCHAR(300),
	CONSTRAINT "pk_ques" PRIMARY KEY (cod)
);

CREATE TABLE q_descritiva(
    cod INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	resposta_esperada VARCHAR(300),
	CONSTRAINT "pk_des" PRIMARY KEY (cod)
) INHERITS(questao);

CREATE TABLE q_objetiva(
    cod INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	resposta_certa VARCHAR(1),
	CONSTRAINT "pk_obj" PRIMARY KEY (cod)
) INHERITS(questao);

CREATE TABLE opcoes(
	cod INTEGER NOT NULL,
	opcao VARCHAR(300) NOT NULL,
	letra VARCHAR(1) NOT NULL,
	CONSTRAINT "pk_opcoes" PRIMARY KEY(cod, opcao),
	CONSTRAINT "fk_opcoes_questoes" FOREIGN KEY(cod)
	REFERENCES questao(cod)
);

CREATE TABLE avaliacao(
	cod INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	descricao VARCHAR(300) NOT NULL,
	data DATE NOT NULL,
	horario TIME NOT NULL,
	valor NUMERIC(4, 2)  NOT NULL CHECK (valor > 0),
	p_cpf VARCHAR(11) NOT NULL,
	CONSTRAINT "pk_ava" PRIMARY KEY(cod),
	CONSTRAINT "fk_ava_prof" FOREIGN KEY(p_cpf)
	REFERENCES professor(cpf)
);	

CREATE TABLE prova_feita(
	cod INTEGER NOT NULL,
	cpf VARCHAR(11) NOT NULL,
	nota_final NUMERIC(4, 2)  NOT NULL CHECK (nota_final BETWEEN 0 AND 10),
	CONSTRAINT "pk_prova" PRIMARY KEY(cod, cpf),
	CONSTRAINT "fk_prova_ava" FOREIGN KEY(cod)
	REFERENCES avaliacao(cod),
	CONSTRAINT "fk_prova_aluno" FOREIGN KEY(cpf)
	REFERENCES aluno(cpf)
);
CREATE TABLE questoes_usadas(
	a_cod INTEGER NOT NULL,
	q_cod INTEGER NOT NULL,
	valor INTEGER NOT NULL CHECK (valor > 0),
	CONSTRAINT "pk_ques_usadas" PRIMARY KEY (a_cod, q_cod),
	CONSTRAINT "fk_ques_usadas_ava" FOREIGN KEY(a_cod)
	REFERENCES avaliacao(cod),
	CONSTRAINT "fk_ques_usadas_ques" FOREIGN KEY(q_cod)
	REFERENCES questao(cod)
);

CREATE TABLE aluno_cursa_disc(
	cod INTEGER NOT NULL,
	cpf VARCHAR(11) NOT NULL,
	CONSTRAINT "pk_acd" PRIMARY KEY(cod, cpf),
	CONSTRAINT "fk_acd_disc" FOREIGN KEY(cod)
	REFERENCES disciplina(cod),
	CONSTRAINT "fk_acd_aluno" FOREIGN KEY(cpf)
	REFERENCES aluno(cpf)
);

CREATE TABLE resposta_dada(
	cpf VARCHAR(11) NOT NULL,
	a_cod INTEGER NOT NULL,
	q_cod INTEGER NOT NULL,
	resposta VARCHAR(300) NOT NULL,
	nota_final NUMERIC(4, 2)  NOT NULL CHECK (nota_final BETWEEN 0 AND 10),
	CONSTRAINT "pk_res" PRIMARY KEY (cpf, a_cod, q_cod),
	CONSTRAINT "fk_res_aluno" FOREIGN KEY(cpf)
	REFERENCES aluno(cpf),
	CONSTRAINT "fk_res_ava" FOREIGN KEY(a_cod)
	REFERENCES avaliacao(cod),
	CONSTRAINT "fk_res_ques" FOREIGN KEY(q_cod)
	REFERENCES questao(cod)
)