# Generated by Django 5.1.14 on 2025-11-16 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('turma', models.CharField(max_length=100)),
                ('semestre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('data_nasc', models.DateField(blank=True, null=True)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('cod', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('OBJETIVA', 'Objetiva'), ('DESCRITIVA', 'Descritiva')], max_length=10)),
                ('pergunta', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('cod', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=300)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('cod', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=300)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('valor_total', models.IntegerField()),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.professor')),
            ],
        ),
        migrations.CreateModel(
            name='QuestaoDescritiva',
            fields=[
                ('questao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.questao')),
                ('resposta_esperada', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'myapp_q_descritiva',
            },
            bases=('myapp.questao',),
        ),
        migrations.CreateModel(
            name='QuestaoObjetiva',
            fields=[
                ('questao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.questao')),
                ('resposta_certa', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'myapp_q_objetiva',
            },
            bases=('myapp.questao',),
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcao_texto', models.CharField(max_length=300)),
                ('letra', models.CharField(max_length=1)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.questao')),
            ],
        ),
        migrations.CreateModel(
            name='AlunoCursaDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.disciplina')),
            ],
            options={
                'unique_together': {('aluno', 'disciplina')},
            },
        ),
        migrations.CreateModel(
            name='ProvaFeita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_final', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.aluno')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.avaliacao')),
            ],
            options={
                'unique_together': {('aluno', 'avaliacao')},
            },
        ),
        migrations.CreateModel(
            name='QuestaoUsada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.avaliacao')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.questao')),
            ],
            options={
                'unique_together': {('avaliacao', 'questao')},
            },
        ),
        migrations.CreateModel(
            name='RespostaDada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=300)),
                ('nota_questao', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.aluno')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.avaliacao')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.questao')),
            ],
            options={
                'unique_together': {('aluno', 'avaliacao', 'questao')},
            },
        ),
    ]
